import React from "react";
import { FlatList, Image, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { Screen } from "../src/ui/Screen";
import { useCustomerHome } from "../src/hooks/useCustomerHome";
import { LoadingState, ErrorState, EmptyState } from "../src/ui/StateViews";
import { SectionHeader } from "../src/ui/SectionHeader";
import { ChefCard } from "../src/ui/ChefCard";
import { DishCard } from "../src/ui/DishCard";
import { BottomNav } from "../src/ui/BottomNav";
import { colors, radius, spacing } from "../src/theme/tokens";
export default function HomeScreen(){const q=useCustomerHome();if(q.isLoading)return <Screen><LoadingState label="بنجهز لك مطبخ اليوم..."/></Screen>;if(q.isError||!q.data)return <Screen><ErrorState message="تعذر تحميل الرئيسية. حاول مرة أخرى."/></Screen>;const data=q.data;return <View style={s.page}><Screen contentStyle={s.content}><View style={s.top}><View style={s.topActions}><Pressable onPress={()=>router.push('/cart')} style={s.cartQuick}><Text style={s.cartQuickText}>🛒</Text></Pressable><Image source={require('../assets/baytna-logo.png')} style={s.logo} resizeMode="contain"/></View><View><Text style={s.hello}>أهلاً بيك 👋</Text><Text style={s.area}>📍 {data.area}</Text></View></View><Pressable onPress={()=>router.push('/chefs')} style={s.search}><Text style={s.searchIcon}>⌕</Text><Text style={s.searchText}>نفسك تاكل إيه النهارده؟</Text></Pressable><SectionHeader title="شيفات مميزون" action="عرض الكل" onAction={()=>router.push('/chefs')}/><FlatList horizontal inverted showsHorizontalScrollIndicator={false} data={data.featured_chefs} keyExtractor={x=>x.id} contentContainerStyle={s.horizontal} renderItem={({item})=><ChefCard chef={item} onPress={()=>router.push(`/chefs/${item.id}`)}/>} ListEmptyComponent={<EmptyState title="مفيش شيفات مفتوحة دلوقتي"/>}/><SectionHeader title={data.today.title} action="قريب منك" onAction={()=>{}}/><View style={s.grid}>{data.today.items.length?data.today.items.map(item=><DishCard key={item.id} item={item} chefName={item.chef_name} onPress={()=>router.push({pathname:'/chefs/[chefId]/dish/[dishId]',params:{chefId:item.chef_id,dishId:item.dish_id,dailyMenuItemId:item.id}})}/>):<EmptyState title="مطبخ اليوم لسه بيجهز" body="ارجع لنا بعد شوية أو شوف قائمة الشيفات."/>}</View></Screen><BottomNav active="home"/></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas},content:{paddingBottom:24},top:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center",paddingTop:10},topActions:{flexDirection:"row-reverse",alignItems:"center",gap:8},cartQuick:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,alignItems:"center",justifyContent:"center"},cartQuickText:{fontSize:20},logo:{width:68,height:68},hello:{fontSize:19,fontWeight:"900",textAlign:"right",writingDirection:"rtl",color:colors.ink},area:{color:colors.muted,textAlign:"right",marginTop:3,writingDirection:"rtl"},search:{height:50,borderRadius:radius.md,backgroundColor:colors.soft,flexDirection:"row-reverse",alignItems:"center",paddingHorizontal:15,gap:10,marginTop:8},searchIcon:{fontSize:23,color:colors.muted},searchText:{flex:1,color:colors.muted,textAlign:"right",writingDirection:"rtl"},horizontal:{gap:12,paddingVertical:4},grid:{flexDirection:"row-reverse",flexWrap:"wrap",gap:12,justifyContent:"space-between"}});
