"""Sprint 30 media attachments, notification templates and provider receipts.
Revision ID: 0015_sprint30
Revises: 0014_sprint29
"""
from alembic import op
import sqlalchemy as sa
revision="0015_sprint30"; down_revision="0014_sprint29"; branch_labels=None; depends_on=None

def upgrade():
    with op.batch_alter_table("dishes", recreate="always") as b:
        b.add_column(sa.Column("media_asset_id",sa.Uuid(),nullable=True)); b.create_foreign_key("fk_dishes_media_asset","media_assets",["media_asset_id"],["id"],ondelete="SET NULL"); b.create_index("ix_dishes_media_asset_id",["media_asset_id"])
    with op.batch_alter_table("delivery_tasks", recreate="always") as b:
        b.add_column(sa.Column("delivery_proof_media_asset_id",sa.Uuid(),nullable=True)); b.create_foreign_key("fk_delivery_proof_media","media_assets",["delivery_proof_media_asset_id"],["id"],ondelete="SET NULL"); b.create_index("ix_delivery_tasks_delivery_proof_media_asset_id",["delivery_proof_media_asset_id"])
    op.create_table("support_message_attachments",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("message_id",sa.Uuid(),nullable=False),sa.Column("media_asset_id",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["message_id"],["support_messages.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["media_asset_id"],["media_assets.id"],ondelete="RESTRICT"),sa.UniqueConstraint("message_id","media_asset_id",name="uq_support_message_attachment"))
    op.create_index("ix_support_message_attachments_message_id","support_message_attachments",["message_id"]); op.create_index("ix_support_message_attachments_media_asset_id","support_message_attachments",["media_asset_id"]); op.create_index("ix_support_message_attachments_message","support_message_attachments",["message_id","created_at"])
    op.create_table("notification_templates",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("kind",sa.String(80),nullable=False,unique=True),sa.Column("title_template",sa.String(180),nullable=False),sa.Column("body_template",sa.Text(),nullable=False),sa.Column("is_enabled",sa.Boolean(),nullable=False),sa.Column("updated_by_admin_id",sa.Uuid(),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["updated_by_admin_id"],["users.id"],ondelete="SET NULL")); op.create_index("ix_notification_templates_kind","notification_templates",["kind"])
    op.create_table("notification_provider_events",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("channel",sa.String(20),nullable=False),sa.Column("provider",sa.String(40),nullable=False),sa.Column("provider_event_id",sa.String(200),nullable=False),sa.Column("provider_message_id",sa.String(200),nullable=False),sa.Column("event_status",sa.String(30),nullable=False),sa.Column("payload_hash",sa.String(64),nullable=False),sa.Column("payload_json",sa.JSON(),nullable=False),sa.Column("processed_at",sa.DateTime(timezone=True),nullable=True),sa.Column("matched_delivery_id",sa.Uuid(),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("channel IN ('push','sms')",name="ck_notification_provider_event_channel"),sa.CheckConstraint("event_status IN ('accepted','delivered','failed','bounced')",name="ck_notification_provider_event_status"),sa.ForeignKeyConstraint(["matched_delivery_id"],["notification_deliveries.id"],ondelete="SET NULL"),sa.UniqueConstraint("provider","provider_event_id",name="uq_notification_provider_event"))
    op.create_index("ix_notification_provider_events_provider_message_id","notification_provider_events",["provider_message_id"]); op.create_index("ix_notification_provider_events_matched_delivery_id","notification_provider_events",["matched_delivery_id"]); op.create_index("ix_provider_events_unprocessed","notification_provider_events",["processed_at","created_at"])

def downgrade():
    op.drop_index("ix_provider_events_unprocessed",table_name="notification_provider_events"); op.drop_index("ix_notification_provider_events_matched_delivery_id",table_name="notification_provider_events"); op.drop_index("ix_notification_provider_events_provider_message_id",table_name="notification_provider_events"); op.drop_table("notification_provider_events")
    op.drop_index("ix_notification_templates_kind",table_name="notification_templates"); op.drop_table("notification_templates")
    op.drop_index("ix_support_message_attachments_message",table_name="support_message_attachments"); op.drop_index("ix_support_message_attachments_media_asset_id",table_name="support_message_attachments"); op.drop_index("ix_support_message_attachments_message_id",table_name="support_message_attachments"); op.drop_table("support_message_attachments")
    with op.batch_alter_table("delivery_tasks", recreate="always") as b: b.drop_index("ix_delivery_tasks_delivery_proof_media_asset_id"); b.drop_constraint("fk_delivery_proof_media",type_="foreignkey"); b.drop_column("delivery_proof_media_asset_id")
    with op.batch_alter_table("dishes", recreate="always") as b: b.drop_index("ix_dishes_media_asset_id"); b.drop_constraint("fk_dishes_media_asset",type_="foreignkey"); b.drop_column("media_asset_id")
