import React, { useMemo, useState } from "react";
import { StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { Screen } from "../../src/ui/Screen";
import { PrimaryButton } from "../../src/ui/PrimaryButton";
import { customerApi } from "../../src/api";
import { ApiClientError } from "../../src/api/http";
import { useAuth } from "../../src/auth/AuthProvider";
import { colors, radius, spacing } from "../../src/theme/tokens";
export default function OtpScreen(){const params=useLocalSearchParams<{phone:string;devOtp?:string}>();const phone=String(params.phone??"");const devOtp=String(params.devOtp??"");const [code,setCode]=useState(devOtp);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const auth=useAuth();const masked=useMemo(()=>phone.length>4?`${phone.slice(0,4)}••••${phone.slice(-3)}`:phone,[phone]);async function verify(){if(code.trim().length<4){setError("اكتب كود التحقق");return;}setLoading(true);setError("");try{await customerApi.verifyOtp(phone,code.trim());auth.signedIn();router.replace('/home');}catch(e){setError(e instanceof ApiClientError?e.message:"الكود غير صحيح أو انتهت صلاحيته");}finally{setLoading(false)}}return <Screen><View style={s.wrap}><Text style={s.icon}>🔐</Text><Text style={s.title}>كود التحقق</Text><Text style={s.subtitle}>بعثنا الكود للرقم {masked}</Text>{devOtp?<View style={s.dev}><Text style={s.devText}>Development OTP: {devOtp}</Text></View>:null}<TextInput value={code} onChangeText={setCode} keyboardType="number-pad" textAlign="center" maxLength={8} style={s.code}/>{error?<Text style={s.error}>{error}</Text>:null}<PrimaryButton label="تأكيد ودخول" onPress={verify} loading={loading}/><Text onPress={()=>router.back()} style={s.back}>تغيير رقم الموبايل</Text></View></Screen>}
const s=StyleSheet.create({wrap:{flex:1,justifyContent:"center",paddingBottom:50},icon:{fontSize:52,textAlign:"center",marginBottom:12},title:{fontSize:28,fontWeight:"900",textAlign:"center",color:colors.ink,writingDirection:"rtl"},subtitle:{color:colors.muted,textAlign:"center",writingDirection:"rtl",marginTop:8,marginBottom:24},code:{height:60,borderWidth:1.5,borderColor:colors.orange,borderRadius:radius.md,backgroundColor:colors.surface,fontSize:26,fontWeight:"900",letterSpacing:8,marginBottom:12},error:{color:colors.danger,textAlign:"center",writingDirection:"rtl",marginBottom:12},back:{color:colors.orangeDark,fontWeight:"800",textAlign:"center",writingDirection:"rtl",marginTop:18},dev:{alignSelf:"center",backgroundColor:colors.orangeSoft,borderRadius:radius.sm,paddingHorizontal:10,paddingVertical:6,marginBottom:12},devText:{color:colors.orangeDark,fontSize:11}});
