import React, { useState } from "react";
import { Image, KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { Screen } from "../../src/ui/Screen";
import { PrimaryButton } from "../../src/ui/PrimaryButton";
import { customerApi } from "../../src/api";
import { ApiClientError } from "../../src/api/http";
import { colors, radius, spacing } from "../../src/theme/tokens";
import { compactPhone } from "../../src/utils/format";
export default function PhoneScreen(){const [phone,setPhone]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");async function submit(){const value=compactPhone(phone);if(value.length<10){setError("اكتب رقم موبايل صحيح");return;}setLoading(true);setError("");try{const r=await customerApi.sendOtp(value);router.push({pathname:"/auth/otp",params:{phone:value,devOtp:r.development_otp??""}});}catch(e){setError(e instanceof ApiClientError?e.message:"تعذر إرسال الكود");}finally{setLoading(false)}}return <Screen><KeyboardAvoidingView behavior={Platform.OS==="ios"?"padding":undefined} style={s.wrap}><Image source={require('../../assets/baytna-logo.png')} style={s.logo} resizeMode="contain"/><Text style={s.title}>أهلاً بيك في بيتنا</Text><Text style={s.subtitle}>ادخل رقم موبايلك علشان نبعث لك كود الدخول</Text><Text style={s.label}>رقم الموبايل</Text><TextInput value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="01xxxxxxxxx" placeholderTextColor="#A99B91" style={s.input} textAlign="right" maxLength={16}/>{error?<Text style={s.error}>{error}</Text>:null}<PrimaryButton label="إرسال الكود" onPress={submit} loading={loading}/><Text style={s.note}>بدخولك أنت توافق على شروط وسياسة خصوصية بيتنا.</Text></KeyboardAvoidingView></Screen>}
const s=StyleSheet.create({wrap:{flex:1,justifyContent:"center",paddingBottom:60},logo:{width:110,height:110,alignSelf:"center",marginBottom:spacing.lg},title:{fontSize:28,fontWeight:"900",color:colors.ink,textAlign:"center",writingDirection:"rtl"},subtitle:{fontSize:15,color:colors.muted,textAlign:"center",writingDirection:"rtl",marginTop:8,marginBottom:32,lineHeight:23},label:{fontWeight:"800",color:colors.ink,textAlign:"right",writingDirection:"rtl",marginBottom:8},input:{height:54,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface,paddingHorizontal:16,fontSize:18,color:colors.ink,marginBottom:12},error:{color:colors.danger,textAlign:"right",writingDirection:"rtl",marginBottom:12},note:{fontSize:11,color:colors.muted,textAlign:"center",writingDirection:"rtl",marginTop:16}});
