export const queryKeys = {
  home: ["customer", "home"] as const,
  chefs: (area?: string, openToday?: boolean) => ["public", "chefs", area ?? null, openToday ?? null] as const,
  chef: (chefId: string) => ["public", "chef", chefId] as const,
  todayMenu: (chefId: string) => ["public", "chef", chefId, "today-menu"] as const,
  signatureMenu: (chefId: string) => ["public", "chef", chefId, "signature-menu"] as const,
  cart: ["customer", "cart"] as const,
  pricing: (cartId: string, coupon: string, loyalty: number) => ["customer", "pricing", cartId, coupon, loyalty] as const,
  addresses: ["customer", "addresses"] as const,
  orders: ["customer", "orders"] as const,
  order: (orderId: string) => ["customer", "order", orderId] as const,
  payment: (orderId: string) => ["customer", "payment", orderId] as const,
  tracking: (orderId: string) => ["customer", "tracking", orderId] as const,
  profile: ["customer", "profile"] as const,
  favorites: ["customer", "favorites"] as const,
  favoriteChefs: ["customer", "favorites", "chefs"] as const,
  favoriteDishes: ["customer", "favorites", "dishes"] as const,
  notifications: ["customer", "notifications"] as const,
  notificationSummary: ["customer", "notifications", "summary"] as const,
  notificationPreferences: ["customer", "notifications", "preferences"] as const,
  loyalty: ["customer", "loyalty"] as const,
  supportTickets: ["customer", "support", "tickets"] as const,
  supportTicket: (ticketId: string) => ["customer", "support", "ticket", ticketId] as const,
  subscriptionPlans: ["customer", "subscriptions", "plans"] as const,
  currentSubscription: ["customer", "subscriptions", "current"] as const,
  reviewEligibility: (orderId: string) => ["customer", "review-eligibility", orderId] as const,
  myReviews: ["customer", "reviews"] as const,
  chefReviews: (chefId: string) => ["public", "chef", chefId, "reviews"] as const,
  chefRatingSummary: (chefId: string) => ["public", "chef", chefId, "rating-summary"] as const,
  chefAvailability: (chefId: string) => ["public", "chef", chefId, "availability"] as const,
  specialOrders: ["customer", "special-orders"] as const,
  specialOrder: (specialOrderId: string) => ["customer", "special-order", specialOrderId] as const,
};
