import {QueryClient} from "@tanstack/react-query";
export const queryClient=new QueryClient({
  defaultOptions:{queries:{staleTime:15000,retry:1,refetchOnWindowFocus:false},mutations:{retry:0}},
});
export const keys={
  profile:["admin","profile"] as const,
  controlRoom:["admin","control-room"] as const,
  pilotPrograms:["admin","pilot","programs"] as const,
  pilotStability:(id:string)=>["admin","pilot",id,"stability"] as const,
  pilotCohorts:(id:string)=>["admin","pilot",id,"cohorts"] as const,
  pilotEvidence:(id:string)=>["admin","pilot",id,"evidence"] as const,
  pilotPost:(id:string)=>["admin","pilot",id,"post"] as const,
  economics:(id:string)=>["admin","economics",id] as const,
  economicsCosts:(id:string)=>["admin","economics",id,"costs"] as const,
  expansionZones:["admin","economics","zones"] as const,
  providerImports:["admin","economics","provider-imports"] as const,
  settlementBatches:["admin","economics","settlements"] as const,
  zoneBudget:(id:string)=>["admin","economics","zone",id,"budget"] as const,
  trafficZones:["admin","traffic","zones"] as const,
  trafficMonitoring:(id:string)=>["admin","traffic",id,"monitoring"] as const,
  trafficForecasts:(id:string)=>["admin","traffic",id,"forecasts"] as const,
  postLaunchSummary:["admin","post-launch","summary"] as const,
  postLaunchReviews:["admin","post-launch","reviews"] as const,
  trafficAdmissions:(id:string)=>["admin","traffic",id,"admissions"] as const,
  vendorAccounting:["admin","vendor-accounting"] as const,
  importReviewQueue:["admin","vendor-accounting","imports"] as const,
  settlementOperations:["admin","vendor-accounting","settlements"] as const,
  launchSessions:["admin","launch-command","sessions"] as const,
  launchOverview:(id:string)=>["admin","launch-command",id,"overview"] as const,
  launchRunbook:(id:string)=>["admin","launch-command",id,"runbook"] as const,
  launchEvents:(id:string)=>["admin","launch-command",id,"events"] as const,
  launchOverrides:(id:string)=>["admin","launch-command",id,"overrides"] as const,
  launchFinancialCloses:(id:string)=>["admin","launch-command",id,"financial-closes"] as const,
  launchRollbackDrills:(id:string)=>["admin","launch-command",id,"rollback-drills"] as const,
  launchEvidencePacks:(id:string)=>["admin","launch-command",id,"evidence-packs"] as const,
  incidents:["admin","control-room","incidents"] as const,
  dailyBrief:["admin","control-room","daily-brief"] as const,
  overview:["admin","overview"] as const,
  orders:(status?:string)=>["admin","orders",status??"all"] as const,
  order:(id:string)=>["admin","order",id] as const,
  chefs:(status?:string)=>["admin","chefs",status??"all"] as const,
  chef:(id:string)=>["admin","chef",id] as const,
  drivers:(status?:string)=>["admin","drivers",status??"all"] as const,
  driver:(id:string)=>["admin","driver",id] as const,
  support:["admin","support"] as const,
  tickets:(status?:string)=>["admin","tickets",status??"all"] as const,
  ticket:(id:string)=>["admin","ticket",id] as const,
  finance:["admin","finance"] as const,
  daily:["admin","analytics","daily"] as const,
  funnel:["admin","analytics","funnel"] as const,
  retention:["admin","analytics","retention"] as const,
  audit:["admin","audit"] as const,
};
