import React from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { ChefSummary } from "../api/types";
import { colors, radius, shadow, spacing } from "../theme/tokens";
export function ChefCard({ chef, compact = false, onPress }: { chef: ChefSummary; compact?: boolean; onPress(): void }) {
  if (compact) return <Pressable onPress={onPress} style={({pressed}) => [s.list, pressed && s.pressed]}><View style={s.avatar}><Text style={s.emoji}>👩‍🍳</Text></View><View style={s.info}><Text style={s.name}>{chef.display_name}</Text><Text style={s.meta}>{chef.specialty}</Text><Text style={s.meta}>★ {chef.rating.toFixed(1)} • {chef.area}</Text></View><Text style={s.arrow}>‹</Text></Pressable>;
  return <Pressable onPress={onPress} style={({pressed}) => [s.card, pressed && s.pressed]}><View style={s.hero}><Text style={s.heroEmoji}>👩‍🍳</Text>{chef.is_verified ? <View style={s.verified}><Text style={s.verifiedText}>✓ موثّق</Text></View> : null}</View><View style={s.body}><Text style={s.name}>{chef.display_name}</Text><Text style={s.meta}>{chef.specialty}</Text><Text style={s.rating}>★ {chef.rating.toFixed(1)}</Text></View></Pressable>;
}
const s=StyleSheet.create({ card:{width:164,borderWidth:1,borderColor:colors.border,borderRadius:radius.card,overflow:"hidden",backgroundColor:colors.surface,...shadow},hero:{height:112,backgroundColor:colors.orangeSoft,alignItems:"center",justifyContent:"center",position:"relative"},heroEmoji:{fontSize:54},verified:{position:"absolute",top:8,right:8,backgroundColor:colors.greenSoft,borderRadius:radius.pill,paddingHorizontal:7,paddingVertical:4},verifiedText:{fontSize:10,color:colors.greenDark,fontWeight:"800"},body:{padding:12},name:{fontWeight:"900",fontSize:15,color:colors.ink,textAlign:"right",writingDirection:"rtl"},meta:{color:colors.muted,fontSize:12,marginTop:3,textAlign:"right",writingDirection:"rtl"},rating:{color:"#8A6200",fontWeight:"800",marginTop:5,textAlign:"right"},list:{minHeight:82,borderWidth:1,borderColor:colors.border,borderRadius:17,backgroundColor:colors.surface,padding:12,flexDirection:"row-reverse",alignItems:"center",gap:12,marginBottom:12},avatar:{width:58,height:58,borderRadius:16,backgroundColor:colors.orangeSoft,alignItems:"center",justifyContent:"center"},emoji:{fontSize:30},info:{flex:1},arrow:{fontSize:28,color:colors.muted},pressed:{opacity:.78}});
