import React, { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { Screen } from "../../src/ui/Screen";
import { useChefs } from "../../src/hooks/useCustomerHome";
import { ChefCard } from "../../src/ui/ChefCard";
import { LoadingState, ErrorState, EmptyState } from "../../src/ui/StateViews";
import { BottomNav } from "../../src/ui/BottomNav";
import { colors, radius, spacing } from "../../src/theme/tokens";
const chips=["الكل","مصري","محاشي","شرقي"];
export default function ChefsScreen(){const [search,setSearch]=useState("");const [chip,setChip]=useState("الكل");const q=useChefs();const filtered=useMemo(()=>{const term=search.trim();return (q.data??[]).filter(c=>{const text=`${c.display_name} ${c.specialty} ${c.area}`;return (!term||text.includes(term))&&(chip==="الكل"||text.includes(chip));});},[q.data,search,chip]);return <View style={s.page}><Screen contentStyle={s.content}><View style={s.appbar}><Pressable onPress={()=>router.back()}><Text style={s.back}>→</Text></Pressable><Text style={s.title}>كل الشيفات</Text><View style={{width:32}}/></View><View style={s.search}><TextInput value={search} onChangeText={setSearch} placeholder="ابحث باسم شيف أو نوع أكل" placeholderTextColor="#9C9087" style={s.input} textAlign="right"/><Text style={s.searchIcon}>⌕</Text></View><View style={s.chips}>{chips.map(x=><Pressable key={x} onPress={()=>setChip(x)} style={[s.chip,chip===x&&s.chipActive]}><Text style={[s.chipText,chip===x&&s.chipTextActive]}>{x}</Text></Pressable>)}</View>{q.isLoading?<LoadingState/>:q.isError?<ErrorState message="تعذر تحميل الشيفات"/>:filtered.length?filtered.map(chef=><ChefCard key={chef.id} chef={chef} compact onPress={()=>router.push(`/chefs/${chef.id}`)}/>):<EmptyState title="مفيش نتائج مطابقة" body="جرّب كلمة بحث أو تصنيف مختلف."/>}</Screen><BottomNav active="chefs"/></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas},content:{paddingBottom:18},appbar:{height:58,flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between"},title:{fontSize:19,fontWeight:"900",color:colors.ink,writingDirection:"rtl"},back:{fontSize:26,color:colors.ink,width:32,textAlign:"center"},search:{height:50,borderRadius:radius.md,backgroundColor:colors.soft,flexDirection:"row-reverse",alignItems:"center",paddingHorizontal:14,marginBottom:12},input:{flex:1,fontSize:14,color:colors.ink},searchIcon:{fontSize:22,color:colors.muted},chips:{flexDirection:"row-reverse",gap:8,marginBottom:16,flexWrap:"wrap"},chip:{paddingHorizontal:12,paddingVertical:8,borderRadius:radius.pill,backgroundColor:colors.soft},chipActive:{backgroundColor:colors.orangeSoft},chipText:{color:colors.muted,fontSize:12},chipTextActive:{color:colors.orangeDark,fontWeight:"900"}});
